### PR TITLE
created collection types for articles and videos in news page

### PR DESCRIPTION
**Pull request by zidano88**

### CODE REVIEW

**Comment by 7ganam** [comment]
image

**Comment by 7ganam** [comment]
image

**Comment by 7ganam** [comment]
image

**Comment by zidano88** [comment]
I made all the changes except for the rich text display part. I could not find it in the option in the front end

**Comment by zidano88** [comment]
Uploading a3{1f92d09} (a1d79278-62e3-4393-9984-329509c885b7 id=0x7f0a03ca tag=BaseCommentFragment) …

**Comment by zidano88** [comment]
Screenshot 2022-09-27 232850

**Pull request merged**
